keys:
  - &macbook age1hph9r83xj7cjh8ydpvl9nstyk35cfe7703jf7z0waj9nzgjz3s3qa39n02

creation_rules:
- path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *
      age:
      - *admin_bob