{         settings.hooks.check-yaml.enable = true;
          settings.hooks.check-json.enable = true;
          settings.hooks.credo.enable = true;
          settings.hooks.detect-aws-credentials.enable = true;
          settings.hooks.detect-private-keys.enable = true;
          settings.hooks.flake-checker.enable = true;
          settings.hooks.gptcommit.enable = true;
          settings.hooks.hlint.enable = true;
          settings.hooks.markdownlint.enable = true;
          settings.hooks.nil.enable = true;
          settings.hooks.ripsecrets.enable = true;
          settings.hooks.treefmt.enable = true;
          settings.hooks.trufflehog.enable = true;}