on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "v2"
      - "v2-*"
    tags:
      - "v2-[0-9]+.[0-9]+*"
name: Nix Code analysis
jobs:
  alejandra:
    name: Alejandra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: Set up Alejandra
      - uses: luisnquin/setup-alejandra@v1.0.0
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
  statix:
    name: Statix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: statix
      - uses: jocelynthode/statix-action@master
