name: "omnix-cachix"
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  omnix-cachix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: "nix run github:juspay/omnix ci --results=om.json"
    - run: "nix run github:juspay/cachix-push -- --cache hyprflake --subflake ROOT --prefix 'v2' < om.json"

