# https://github.com/wimpysworld/nix-config/blob/main/.github/workflows/flake-checker.yml
name: Flake ❄️ Checker ✅

on:
  schedule:
    - cron: '00 */3 * * *'
  workflow_dispatch:
  pull_request:
  push:
    branches:

    - "v2"
    - "v2-*"
    tags:
    - "v2-[0-9]+.[0-9]+*"
env:
  RUST_BACKTRACE: full

env:
  RUST_BACKTRACE: full

jobs:
  flake-checker:
    name: Flake Checker
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          determinate: true
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: DeterminateSystems/flake-checker-action@v9