name: "omnix-health"
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  omnix-health:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: "nix run github:juspay/omnix health"

